name: ci_ubuntu

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --profile=fast
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: biliroaming-rust-speedtest-${{ github.run_number }}
        path: |
          ./target/fast/biliroaming_rust_speedtest
